# Generated by Django 4.2.23 on 2026-07-11 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('api_key', models.CharField(max_length=500, verbose_name='API ключ')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('base_url', models.URLField(verbose_name='API endpoint')),
                ('role', models.CharField(choices=[('genius', 'Гений (особо умная)'), ('smart', 'Умная'), ('smart-alt', 'Умная (альт.)'), ('cheap', 'Дешёвая'), ('embed', 'Эмбеддинг'), ('vision', 'Vision (фото)')], default='smart', max_length=10, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('timeout', models.PositiveIntegerField(default=90, verbose_name='Таймаут (сек)')),
                ('temperature', models.FloatField(default=0.3, verbose_name='Temperature')),
            ],
            options={
                'verbose_name': 'AI провайдер',
                'verbose_name_plural': 'AI провайдеры',
            },
        ),
        migrations.CreateModel(
            name='ProxySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('host', models.CharField(blank=True, max_length=200, verbose_name='IP / хост')),
                ('port', models.PositiveIntegerField(default=63094, verbose_name='HTTP порт')),
                ('username', models.CharField(blank=True, max_length=200, verbose_name='Пользователь')),
                ('password', models.CharField(blank=True, max_length=200, verbose_name='Пароль')),
                ('is_active', models.BooleanField(default=False, verbose_name='Использовать для запросов к ИИ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Прокси',
                'verbose_name_plural': 'Прокси',
            },
        ),
        migrations.CreateModel(
            name='AIProviderTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тег')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='aicore.aiprovider')),
            ],
            options={
                'verbose_name': 'Тег провайдера',
                'verbose_name_plural': 'Теги провайдера',
                'unique_together': {('provider', 'name')},
            },
        ),
    ]
