# Generated by Django 4.2.23 on 2026-07-12 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aicore", '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('kind', models.CharField(choices=[('chat', 'Чат'), ('embedding', 'Эмбеддинг')], default='chat', max_length=10, verbose_name='Тип вызова')),
                ('caller', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Вызывающий')),
                ('role', models.CharField(blank=True, max_length=20, verbose_name='Роль')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Модель')),
                ('upstream', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Хостер')),
                ('proxy_label', models.CharField(blank=True, max_length=200, verbose_name='Прокси (снимок)')),
                ('ok', models.BooleanField(db_index=True, default=False, verbose_name='Успех')),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP')),
                ('finish_reason', models.CharField(blank=True, max_length=50, verbose_name='finish_reason')),
                ('error_kind', models.CharField(blank=True, db_index=True, max_length=30, verbose_name='Фаза отказа')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='Токены промпта')),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='Токены ответа')),
                ('reasoning_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='Токены рассуждений')),
                ('duration_s', models.FloatField(blank=True, null=True, verbose_name='Длительность, с')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aicore.aiprovider', verbose_name='Провайдер')),
                ('proxy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aicore.proxysettings', verbose_name='Прокси')),
            ],
            options={
                'verbose_name': 'Вызов AI',
                'verbose_name_plural': 'Журнал вызовов AI',
                'ordering': ['-created_at'],
            },
        ),
    ]
