# Generated by Django 5.2.3 on 2026-07-14 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_aicore', '0002_aicalllog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AITask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='Ключ (стабильный)')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название')),
                ('default_role', models.CharField(blank=True, max_length=20, verbose_name='Роль из кода')),
                ('default_temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature из кода')),
                ('tag', models.CharField(blank=True, max_length=100, verbose_name='Тег провайдера')),
                ('role', models.CharField(blank=True, choices=[('genius', 'Гений (особо умная)'), ('smart', 'Умная'), ('smart-alt', 'Умная (альт.)'), ('cheap', 'Дешёвая'), ('embed', 'Эмбеддинг'), ('vision', 'Vision (фото)')], max_length=20, verbose_name='Роль (замена)')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Temperature (замена)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирована')),
            ],
            options={
                'verbose_name': 'AI задача',
                'verbose_name_plural': 'AI задачи',
                'ordering': ['key'],
            },
        ),
        migrations.AlterModelOptions(
            name='aiprovider',
            options={'ordering': ['priority', 'id'], 'verbose_name': 'AI провайдер', 'verbose_name_plural': 'AI провайдеры'},
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='priority',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Приоритет (меньше — раньше)'),
        ),
        migrations.AddField(
            model_name='aicalllog',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_aicore.aitask', verbose_name='Задача'),
        ),
    ]
