# Generated by Django 5.2.3 on 2026-07-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_aicore', '0003_aitask_alter_aiprovider_options_aiprovider_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxysettings',
            name='fails',
            field=models.PositiveIntegerField(default=0, verbose_name='Ошибок'),
        ),
    ]
