# Generated by Django 5.2.3 on 2026-07-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_aicore', '0004_proxysettings_fails'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxysettings',
            name='oks',
            field=models.PositiveIntegerField(default=0, verbose_name='Успехов'),
        ),
        migrations.AlterField(
            model_name='proxysettings',
            name='fails',
            field=models.PositiveIntegerField(default=0, verbose_name='Сбоев'),
        ),
    ]
