# Generated by Django 5.2.3 on 2026-08-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_aicore', '0007_aiprovider_dialect'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicalllog',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Стоимость, $'),
        ),
        migrations.AddField(
            model_name='aicalllog',
            name='gen_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='id генерации'),
        ),
    ]
