# Generated by Django 5.2.3 on 2026-08-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_aicore', '0008_aicalllog_cost_aicalllog_gen_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxysettings',
            name='expires_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
