# Generated by Django 5.2.3 on 2026-08-30 12:00

from django.db import migrations, models


def fill_app_from_task_key(apps, schema_editor):
    """Разовый бэкфилл старых строк: приложение восстанавливается из префикса ключа
    задачи — это единственное, что о них известно задним числом.

    Строки без задачи (легаси-`call()`, эмбеддинги) остаются пустыми: приложение у них
    было, но нигде не записано, и придумывать его нельзя. Дальше все новые строки пишет
    `resolve_app`, поэтому пустых со временем не прибавляется.
    """
    AICallLog = apps.get_model("aicore", "AICallLog")
    AITask = apps.get_model("aicore", "AITask")
    for key, pk in AITask.objects.values_list("key", "pk"):
        prefix = key.split(".", 1)[0]
        if prefix and prefix != key:
            AICallLog.objects.filter(task_id=pk).update(app=prefix[:50])


class Migration(migrations.Migration):

    dependencies = [
        ('aicore', '0009_proxysettings_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicalllog',
            name='app',
            field=models.CharField(blank=True, db_index=True, max_length=50, verbose_name='Приложение'),
        ),
        migrations.RunPython(fill_app_from_task_key, migrations.RunPython.noop),
    ]
